# Generated by Django 5.0 on 2023-12-11 12:58

import mapbox_location_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_plus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
        ),
    ]
