# Generated by Django 4.2.1 on 2023-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_plus', '0002_somelocationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255)),
                ('price_class', models.CharField(max_length=255)),
                ('origins', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('last_modified', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='SomeLocationModel',
        ),
    ]
