# Generated by Django 4.2.1 on 2023-12-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_plus', '0003_inventory_delete_somelocationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='price_class',
            new_name='regions',
        ),
    ]
