# Generated by Django 4.2.1 on 2023-12-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_plus', '0004_rename_price_class_inventory_regions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='type',
            new_name='state',
        ),
    ]
