# Generated by Django 5.0 on 2023-12-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_plus', '0005_rename_type_inventory_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('cname', models.CharField(max_length=255)),
                ('ttl', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('associated_distribution', models.CharField(default='No distribution', max_length=255)),
            ],
            options={
                'unique_together': {('domain', 'cname')},
            },
        ),
    ]
